# Generated by Django 5.1.4 on 2025-01-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0022_remove_consultorio_peso_con_consultorio_nota_con'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultorio',
            name='nacimiento_con',
        ),
    ]
