# Generated by Django 5.1.4 on 2025-01-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0023_remove_consultorio_nacimiento_con'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultorio',
            name='nacimiento_con',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
