# Generated by Django 5.1.4 on 2025-01-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0025_auditoria_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='usuario',
        ),
    ]
