# Generated by Django 5.1.4 on 2025-01-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_citas_estado_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='nota_cit',
            field=models.TextField(blank=True, null=True, verbose_name='Nota adicional'),
        ),
    ]
